In [3]:
import pandas as pd
import seaborn as sns
import numpy as np
from sklearn import linear_model

# Creating dataframe

In [4]:
data = {
    'age' : [25,30,35,40,45],
    'premium': [18000, 32000, 40000, 47000, 55000]
}
df = pd.DataFrame(data)
df

age  premium
0   25    18000
1   30    32000
2   35    40000
3   40    47000
4   45    55000

In [5]:
sns.lmplot(x='age', y='premium', data=df)

In [6]:
model = linear_model.LinearRegression()

In [26]:
df['age']

0    25
1    30
2    35
3    40
4    45
Name: age, dtype: int64

In [34]:
y = df['premium']
y

0    18000
1    32000
2    40000
3    47000
4    55000
Name: premium, dtype: int64

In [35]:
model.fit(df[['age']], df[['premium']])  #takes data as double array

LinearRegression()

In [36]:
model.predict([[32]])

C:\Users\Simrah Khan\anc\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[33060.]])

In [37]:
model.predict([[41]])

C:\Users\Simrah Khan\anc\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[49080.]])

In [39]:
model.coef_  #value of slope

array([[1780.]])

In [40]:
model.intercept_   #intercept

array([-23900.])